In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
file = '/home/mytsl02451/New_folder/bank_churn/Churn_Modelling.csv'
df = pd.read_csv(file)

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.shape

(10000, 14)

In [5]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [7]:
df.drop(columns=['RowNumber',  'CustomerId',  'Surname'],inplace=True)

In [8]:
df.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [9]:
df['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [10]:
df['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [11]:
df = pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)

In [12]:
print(df.columns)
df.head()

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Geography_Germany',
       'Geography_Spain', 'Gender_Male'],
      dtype='object')


CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0               1        101348.88       1                  0   
1               1        112542.58       0                  0   
2               0        113931.57       1                  0   
3               0         93826.63       0                  0   
4               1         79084.10       0                  0   

   Geography_Spain  Gender_Male  
0                0            0  
1                1            0  
2                0            0  
3                0            0  
4                1            0

In [13]:
X = df.drop(columns=['Exited'])
y = df['Exited'].values

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test =train_test_split(X,y, test_size=0.2, random_state=0)

In [15]:
print('X_train :',len(X_train))
print('X_test :',len(X_test))
print('y_train :',len(y_train))
print('y_test :',len(y_test))

X_train : 8000
X_test : 2000
y_train : 8000
y_test : 2000


In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_sclaed = scaler.transform(X_test)

In [17]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

2023-04-08 12:27:02.135925: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-08 12:27:02.297289: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-04-08 12:27:02.300615: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-04-08 12:27:02.300632: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore 

In [18]:
model = Sequential()

model.add(Dense(11,activation='sigmoid',input_dim=11))
model.add(Dense(11,activation='sigmoid'))
model.add(Dense(1,activation='sigmoid'))

2023-04-08 12:27:04.924742: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-04-08 12:27:04.924768: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-04-08 12:27:04.924789: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (MYTSL02451): /proc/driver/nvidia/version does not exist
2023-04-08 12:27:04.925016: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 11)                132       
                                                                 
 dense_1 (Dense)             (None, 11)                132       
                                                                 
 dense_2 (Dense)             (None, 1)                 12        
                                                                 
Total params: 276
Trainable params: 276
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.compile(loss='binary_crossentropy',optimizer='Adam',metrics=['Accuracy'])

In [21]:
history = model.fit(X_train_scaled,y_train, epochs=100, validation_split=0.2) #epochs=10

Epoch 1/100
200/200 [==============================] - 1s 2ms/step - loss: 0.4982 - Accuracy: 0.7958 - val_loss: 0.4895 - val_Accuracy: 0.7969
Epoch 2/100
200/200 [==============================] - 0s 1ms/step - loss: 0.4788 - Accuracy: 0.7958 - val_loss: 0.4680 - val_Accuracy: 0.7969
Epoch 3/100
200/200 [==============================] - 0s 1ms/step - loss: 0.4557 - Accuracy: 0.7958 - val_loss: 0.4484 - val_Accuracy: 0.7969
Epoch 4/100
200/200 [==============================] - 0s 1ms/step - loss: 0.4387 - Accuracy: 0.7958 - val_loss: 0.4381 - val_Accuracy: 0.7956
Epoch 5/100
200/200 [==============================] - 0s 1ms/step - loss: 0.4304 - Accuracy: 0.8030 - val_loss: 0.4347 - val_Accuracy: 0.8000
Epoch 6/100
200/200 [==============================] - 0s 2ms/step - loss: 0.4272 - Accuracy: 0.8039 - val_loss: 0.4337 - val_Accuracy: 0.8044
Epoch 7/100
200/200 [==============================] - 0s 1ms/step - loss: 0.4259 - Accuracy: 0.8050 - val_loss: 0.4329 - val_Accuracy: 0.8075

In [45]:
# to view the weights of the layer
model.layers[2].weights

[<tf.Variable 'dense_7/kernel:0' shape=(11, 1) dtype=float32, numpy=
 array([[ 1.4786532],
        [ 1.4668144],
        [ 1.8415023],
        [ 1.6823336],
        [ 1.9780247],
        [-1.7435079],
        [-1.7289215],
        [ 1.6421887],
        [-1.6451018],
        [ 1.5255067],
        [-1.2958552]], dtype=float32)>,
 <tf.Variable 'dense_7/bias:0' shape=(1,) dtype=float32, numpy=array([-0.18052067], dtype=float32)>]

In [46]:
model.predict(X_test_sclaed)

63/63 [==============================] - 0s 973us/step


array([[0.26888797],
       [0.2153129 ],
       [0.09951095],
       ...,
       [0.1295613 ],
       [0.1406464 ],
       [0.23070297]], dtype=float32)

In [ ]:
y_pred = model.predict(X_test_sclaed)

In [47]:
# y_log = model.predict(X_test_sclaed)
# y_log
# y_pred = np.where(y_log>0.5,1,0)

63/63 [==============================] - 0s 750us/step


array([[0.26888797],
       [0.2153129 ],
       [0.09951095],
       ...,
       [0.1295613 ],
       [0.1406464 ],
       [0.23070297]], dtype=float32)

In [55]:
y_pred = y_pred.argmax(axis=-1)

In [49]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.862

In [50]:
import matplotlib.pyplot as plt

In [52]:
history.history

NameError: name 'history' is not defined

In [53]:
plt.plot(history.history['loss'])

NameError: name 'history' is not defined

In [ ]:
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

In [ ]:
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])